---
repos:
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.17.3
    hooks:
      - id: cspell
        name: cspell
        args: ["--no-progress", "--no-summary"]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-cli2

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker
        alias: ec
